sudo: false
language: node_js
node_js:
  - "4"
  - "6"

before_install:
  - travis_retry npm install npm -g

before_install:
  - travis_retry npm install -g npm@2.5.1
  - travis_retry npm install

script:
  - npm test

after_script:
  - npm run cover
  - npm run coveralls

